version: "3.7"
services:
  RsyncRonDocker:
  # build from my github repository at github.com/tzom/RsyncRonDocker
    build: github.com/tzom/RsyncRonDocker.git
    restart: unless-stopped
    environment:
      - SOURCE_DIR=/source
      - DEST_DIR=/destination
    volumes:
      - PATH_TO_SOURCE_VOLUME_AT_HOST:/source
      - PATH_TO_DESTINATION_VOLUME_AT_HOST:/destination    

volumes:
  PATH_TO_SOURCE_VOLUME_AT_HOST:
    external: true
  PATH_TO_DESTINATION_VOLUME_AT_HOST:
    external: true
